In [20]:
import pandas as pd 

In [21]:
data = pd.read_csv("data/heart_disease_uci.csv", index_col = 0)
data.head()

age     sex    dataset               cp  trestbps   chol    fbs  \
id                                                                    
1    63    Male  Cleveland   typical angina     145.0  233.0   True   
2    67    Male  Cleveland     asymptomatic     160.0  286.0  False   
3    67    Male  Cleveland     asymptomatic     120.0  229.0  False   
4    37    Male  Cleveland      non-anginal     130.0  250.0  False   
5    41  Female  Cleveland  atypical angina     130.0  204.0  False   

           restecg  thalch  exang  oldpeak        slope   ca  \
id                                                             
1   lv hypertrophy   150.0  False      2.3  downsloping  0.0   
2   lv hypertrophy   108.0   True      1.5         flat  3.0   
3   lv hypertrophy   129.0   True      2.6         flat  2.0   
4           normal   187.0  False      3.5  downsloping  0.0   
5   lv hypertrophy   172.0  False      1.4    upsloping  0.0   

                 thal  num  
id                          
1        fixed defect    0  
2              normal    2  
3   reversable defect    1  
4              normal    0  
5              normal    0

In [22]:
data.shape

(920, 15)

In [23]:
data.isna().sum()

age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

stats: 

In [24]:
data.describe()

age    trestbps        chol      thalch     oldpeak          ca  \
count  920.000000  861.000000  890.000000  865.000000  858.000000  309.000000   
mean    53.510870  132.132404  199.130337  137.545665    0.878788    0.676375   
std      9.424685   19.066070  110.780810   25.926276    1.091226    0.935653   
min     28.000000    0.000000    0.000000   60.000000   -2.600000    0.000000   
25%     47.000000  120.000000  175.000000  120.000000    0.000000    0.000000   
50%     54.000000  130.000000  223.000000  140.000000    0.500000    0.000000   
75%     60.000000  140.000000  268.000000  157.000000    1.500000    1.000000   
max     77.000000  200.000000  603.000000  202.000000    6.200000    3.000000   

              num  
count  920.000000  
mean     0.995652  
std      1.142693  
min      0.000000  
25%      0.000000  
50%      1.000000  
75%      2.000000  
max      4.000000

distribution of `num`: 

In [25]:
data["num"].value_counts()

num
0    411
1    265
2    109
3    107
4     28
Name: count, dtype: int64

binarization of target variable (`num`):

In [ ]:
#if we don't copy we would modify original data and when running this cell alone we won't get what's intended
binary_data = data.copy()
binary_data["num"] = binary_data["num"] != 0
binary_data["num"] = binary_data["num"].astype(int)
binary_data["num"].value_counts()

num
1    509
0    411
Name: count, dtype: int64

the dataset now became somehow balanced (509 vs 411).

In [32]:
binary_data.apply(lambda col: col.unique())

age         [63, 67, 37, 41, 56, 62, 57, 53, 44, 52, 48, 5...
sex                                            [Male, Female]
dataset      [Cleveland, Hungary, Switzerland, VA Long Beach]
cp          [typical angina, asymptomatic, non-anginal, at...
trestbps    [145.0, 160.0, 120.0, 130.0, 140.0, 172.0, 150...
chol        [233.0, 286.0, 229.0, 250.0, 204.0, 236.0, 268...
fbs                                        [True, False, nan]
restecg       [lv hypertrophy, normal, st-t abnormality, nan]
thalch      [150.0, 108.0, 129.0, 187.0, 172.0, 178.0, 160...
exang                                      [False, True, nan]
oldpeak     [2.3, 1.5, 2.6, 3.5, 1.4, 0.8, 3.6, 0.6, 3.1, ...
slope                     [downsloping, flat, upsloping, nan]
ca                                  [0.0, 3.0, 2.0, 1.0, nan]
thal           [fixed defect, normal, reversable defect, nan]
num                                                    [0, 1]
dtype: object